service: opa-terraform

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  timeout: 10

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./opa/**

functions:
  opa:
    handler: bin/opa
    events:
      - http:
          path: opa
          method: post
